# Generated by Django 5.0.3 on 2024-03-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typedivision', models.CharField(max_length=100)),
                ('subdivision_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('representatives', models.TextField()),
                ('cp', models.CharField(max_length=10)),
            ],
        ),
    ]
