# Generated by Django 5.0.3 on 2024-04-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_neigbor_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neigbor',
            name='id_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subdivision'),
        ),
    ]
