# Generated by Django 5.0.3 on 2024-05-01 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_neigbor_id_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='id_subdivision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.subdivision'),
            preserve_default=False,
        ),
    ]
