# Generated by Django 5.0.3 on 2024-05-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_street_id_subdivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neigbor',
            name='id_subdivision',
        ),
    ]
