# Generated by Django 5.0.3 on 2024-05-01 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_neigbor_id_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=200)),
                ('id_subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='SubdividionUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('id_neigbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.neigbor')),
                ('id_subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subdivision')),
            ],
        ),
    ]
