# Generated by Django 5.0.3 on 2024-05-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_adminusers_subdividionusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdivisionNumberDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name_subdivision', models.CharField(max_length=250)),
            ],
        ),
    ]
